### ISSUE TITLE
Odd positioning of background SVG images

### ISSUE THREAD

**Issue by rgant** [rgant/rob.gant.ninja#6]
<img width="1161" alt="Image" src="https://github.com/user-attachments/assets/1dc5d071-f993-46c9-affd-a0b61d7f5558" />

The SVG backgrounds for `.subsection` are not being positioned at the bottom of the viewport in certain circumstances where the width isn't great enough. I believe this has to do with the `background-size` being set to stretch the SVG image, but the SVG using uniform scaling with an origin at the top left corner. Perhaps `translateY` could be used to always move the image to the bottom of the area. But that is for later.

**Comment by rgant** [comment]
This worked when viewing the SVG image directly, but not as a background image:

```css
    svg {
      position: absolute;
      inset-block-end: 0;
      block-size: auto;
    }
```
